[versions]
agp = "8.13.0"
ben-manes-versions = "0.54.0"
firebase-bom = "34.13.0"
firebase-crashlytics-gradle = "3.0.7"
google-services = "4.4.4"
version-catalog-update = "1.1.0"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
