default_platform(:android)

platform :android do

  desc "Build internal version"
  lane :internal do
    build_android_app(task: "clean")
    build_android_app(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file"     => ENV['STORE_FILE'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias"      => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password"   => ENV['KEY_PASSWORD'],
      }
    )
  end

  desc "Deploy Internal to Google Play"
  lane :internal_googleplay do
    upload_to_play_store(
      release_status: 'draft',
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

  desc "Build beta version"
  lane :beta do
    build_android_app(task: "clean")
    build_android_app(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file"     => ENV['STORE_FILE'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias"      => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password"   => ENV['KEY_PASSWORD'],
      }
    )
  end

  desc "Deploy Beta to Google Play"
  lane :beta_googleplay do
    upload_to_play_store(
      release_status: 'draft',
      track: 'beta',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

  desc "Build production version"
  lane :prod do
    build_android_app(task: "clean")
    build_android_app(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file"     => ENV['STORE_FILE'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias"      => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password"   => ENV['KEY_PASSWORD'],
      }
    )
  end

  desc "Deploy Production to Google Play"
  lane :prod_googleplay do
    upload_to_play_store(
      release_status: 'draft',
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

end
